support properties in the cli

diff --git a/tasks/openstack/add-image/amazon-linux-2023-64/task.yaml b/tasks/openstack/add-image/amazon-linux-2023-64/task.yaml
--- a/tasks/openstack/add-image/amazon-linux-2023-64/task.yaml
+++ b/tasks/openstack/add-image/amazon-linux-2023-64/task.yaml
@@ -9,7 +9,63 @@ environment:
 execute: |
     source_image_name="$(basename $IMAGE_URL)"
     wget -q -O "$IMAGE_NAME" "$IMAGE_URL"
-    gsutil cp "$IMAGE_NAME" gs://snapd-spread-tests/images/openstack/"$IMAGE_NAME"
+
+    # Install test dependencies
+    apt install -y qemu-utils
+
+    # Get the raw image    
+    qemu-img convert -O raw "$IMAGE_NAME" disk.raw
+
+    # Get /dev/sda1 parition offset
+    OFFSET=$( sfdisk -J disk.raw | jq '.partitiontable.partitions[0].start * 512' )
+
+    if [ -z $OFFSET ]; then
+        echo "failed to calculate offset"
+        exit 1
+    fi
+
+    # Either become root and paste these line-by-line or the whole block at once
+    OFFSET="$OFFSET" sh -c '\
+    # Make mounting directory
+    mkdir -p /mnt/disk
+    # Mount the image and prepare the chroot
+    mount -o offset=$OFFSET disk.raw /mnt/disk
+    mount -t proc /proc /mnt/disk/proc
+    mount --rbind /sys /mnt/disk/sys
+    mount --make-rslave /mnt/disk/sys
+    mount --rbind /dev /mnt/disk/dev
+    mount --make-rslave /mnt/disk/dev'
+
+    # Copy nameservers
+    cp /etc/resolv.conf /mnt/disk/etc/
+
+    chroot /mnt/disk /bin/bash -c "yum --nogpgcheck makecache"
+    chroot /mnt/disk /bin/bash -c "yum install -y cloud-init"
+
+    # The default dns server is not working properly in google
+    # so we force using also 8.8.8.8
+    echo "nameserver 8.8.8.8" | tee -a /mnt/disk/etc/resolv.conf
+
+    # Configure time
+    chroot /mnt/disk /bin/bash -c "ln -sf /usr/share/zoneinfo/UTC /etc/localtime"
+
+    # Configure ssh
+    mkdir -p /mnt/disk/etc/ssh/sshd_config.d
+    sed -i 's/^\s*#\?\s*\(PermitRootLogin\|PasswordAuthentication\)\>.*/\1 yes/' /mnt/disk/etc/ssh/sshd_config
+    echo 'PermitRootLogin=yes' > /mnt/disk/etc/ssh/sshd_config.d/00-spread.conf
+    echo 'PasswordAuthentication=yes' >> /mnt/disk/etc/ssh/sshd_config.d/00-spread.conf
+
+    # Update grub Config
+    chroot /mnt/disk /bin/bash -c "sed -i -e 's/GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT=\"console=ttyS0,115200n8\"/g' /etc/default/grub"
+    chroot /mnt/disk /bin/bash -c "grub2-mkconfig -o /boot/grub2/grub.cfg"
+
+    # Create the disk image
+    sleep 30
+    umount -AR /mnt/disk
+    sleep 30    
+    qemu-img convert -O qcow2 disk.raw "$IMAGE_NAME"
+
+    gsutil cp "$IMAGE_NAME" gs://snapd-spread-tests/images/openstack/"$IMAGE_NAME"  
 
 restore: |
     # Remove the project path content
