New scripts for google images

diff --git a/spread.yaml b/spread.yaml
--- a/spread.yaml
+++ b/spread.yaml
@@ -1,6 +1,41 @@
 project: spread-images
 
+environment:
+    PROJECT_PATH: /root/spread
+    TESTSLIB: $PROJECT_PATH/lib
+
 backends:
+
+    google:
+        key: "$(HOST: echo $SPREAD_GOOGLE_KEY)"
+        location: computeengine/us-east1-b
+        systems:
+            - ubuntu-14.04-64:
+                workers: 6
+            - ubuntu-16.04-32:
+                workers: 6
+            - ubuntu-16.04-64:
+                workers: 8
+            - ubuntu-18.04-64:
+                image: ubuntu-os-cloud-devel/daily-ubuntu-1804-bionic-v20180315
+                workers: 6
+
+            - ubuntu-core-16-64:
+                image: ubuntu-16.04-64
+                workers: 6
+
+            - debian-9-64:
+                image: debian-9-stretch
+                workers: 6
+
+            - opensuse-42.2-64:
+                image: opensuse-leap-42-2
+                workers: 4
+                manual: true
+            - opensuse-42.3-64:
+                image: opensuse-cloud/opensuse-leap-42-3-v20180116
+                workers: 4
+
     linode:
         key: "$(HOST: echo $SPREAD_LINODE_KEY)"
         systems:
@@ -36,5 +71,20 @@ restore: |
         /root/spread
 
 suites:
-    tasks/:
-        summary: Image maintenace tasks
+    tasks/google/:
+        summary: Create and update images for google backend
+        environment:
+            GCE_PROJECT: computeengine
+            ZONE: us-east1-b
+        prepare: |
+            . "$TESTSLIB/pkgdb.sh"
+            if ! [ -f "$PROJECT_PATH/sa.json" ]; then
+                echo "Service account file not found in root path"
+                exit 1
+            fi            
+            gcloud auth activate-service-account --key-file="$PROJECT_PATH/sa.json"
+
+            install_pkg_dependencies
+
+    tasks/linode/:
+        summary: Update images for Linode backend
