Install/update packages as part of the images update
This change is done to install the snapd test dependencies as part of
the spread images. Also have been includede images for fedora and
opensuse. This change will help to speed up test suite preparation.

diff --git a/spread.yaml b/spread.yaml
--- a/spread.yaml
+++ b/spread.yaml
@@ -16,17 +16,40 @@ backends:
                 kernel: GRUB 2
             - debian-unstable-64:
                 kernel: GRUB 2
+            - fedora-25-64
+            - opensuse-42.2-64
 
 path: /root/spread
 
 restore: |
-    apt autoremove -y
-
-    find \
-        /var/log \
-        /var/cache/apt \
-        /var/lib/apt/{lists,mirrors} \
-        -type f -exec rm -f {} \;
+    case "$SPREAD_SYSTEM" in
+        ubuntu-*|debian-*)
+            apt autoremove -y
+            find \
+                /var/log \
+                /var/cache/apt \
+                /var/lib/apt/{lists,mirrors} \
+                -type f -exec rm -f {} \;
+            ;;
+        fedora-*)
+            dnf -q -y autoremove
+            find \
+                /var/log \
+                /var/cache/dnf \
+                /var/lib/dnf/{history,yumdb} \
+                -type f -exec rm -f {} \;
+            ;;
+        opensuse-*)
+            find \
+                /var/log \
+                /var/cache/zypper \
+                -type f -exec rm -f {} \;
+            ;;
+        *)
+            echo "ERROR: Unsupported distribution '$SPREAD_SYSTEM'"
+            exit 1
+            ;;
+    esac
 
     rm -rf \
         /root/.bash_history \
