New scripts to update fedora base and fedora 29 images

diff --git a/tasks/google/update-fedora-29-64-base/task.yaml b/tasks/google/update-fedora-29-64-base/task.yaml
--- a/tasks/google/update-fedora-29-64-base/task.yaml
+++ b/tasks/google/update-fedora-29-64-base/task.yaml
@@ -1,9 +1,9 @@
-summary: Update fedora image with the latest updates and test dependencies with selinux permissive
+summary: Update fedora base image with the latest updates
 
 systems: [fedora-29-64-base]
 
 environment:
-    TARGET_SYSTEM: fedora-29-64
+    TARGET_SYSTEM: fedora-29-64-base
 
 execute: |
     . "$TESTSLIB/google.sh"
@@ -12,18 +12,22 @@ execute: |
     . "$TESTSLIB/utils.sh"
 
     if [ "$SPREAD_REBOOT" = 0 ]; then
-        # Make the upgrade and install the dependencies needed to run snapd tests
         distro_update_package_db
         distro_upgrade_packages
-        install_test_dependencies "$TARGET_SYSTEM"
-        remove_pkg_blacklist
         distro_clean_package_cache
+
+        # Disable google-network-daemon service because it conflicts with spread ssh configuration during startup
+        systemctl disable --now google-network-daemon.service || true
+
+        # Disable cloud init because reset sshd config affecting spread metadata script
+        # Also in fedora 29 cloud-init fails on start
+        touch /etc/cloud/cloud-init.disabled
 
         REBOOT
     fi
 
-    # Set selinux as permissive
-    sed -i 's/SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
+    # Purge old kernel package
+    distro_purge_package kernel-core-4.18.16-300.fc29.x86_64
 
     # Clean disk before create the shapshot
     clean_machine
