Use jq to calculate /dev/sda1 offset

diff --git a/tasks/google/add-amazon-linux-2/task.yaml b/tasks/google/add-amazon-linux-2/task.yaml
--- a/tasks/google/add-amazon-linux-2/task.yaml
+++ b/tasks/google/add-amazon-linux-2/task.yaml
@@ -18,8 +18,13 @@ execute: |
     wget -O "${IMAGE_FILE}.qcow2" "$IMAGE_URL"
     qemu-img convert -O raw "${IMAGE_FILE}.qcow2" "$DISK_NAME"
 
-    # Get /dev/sda1 parition offset:
-    OFFSET=$( sfdisk -J "$DISK_NAME" | python -c 'import sys, json; a=json.load(sys.stdin); print(a["partitiontable"]["partitions"][0]["start"]*512)' )
+    # Get /dev/sda1 parition offset
+    OFFSET=$( sfdisk -J "$DISK_NAME" | jq '.partitiontable.partitions[0].start * 512' )
+
+    if [ -z $OFFSET ]; then
+        echo "failed to calculate offset"
+        exit 1
+    fi
 
     # Either become root and paste these line-by-line or the whole block at once
     OFFSET="$OFFSET" sh -c '\
diff --git a/tasks/google/add-fedora-27-64/task.yaml b/tasks/google/add-fedora-27-64/task.yaml
--- a/tasks/google/add-fedora-27-64/task.yaml
+++ b/tasks/google/add-fedora-27-64/task.yaml
@@ -17,8 +17,13 @@ execute: |
     # Get the image
     wget -O - "$IMAGE_URL" | xz -cd - > disk.raw
 
-    # Get /dev/sda1 parition offset:
-    OFFSET=$( sfdisk -J disk.raw | python -c 'import sys, json; a=json.load(sys.stdin); print(a["partitiontable"]["partitions"][0]["start"]*512)' )
+    # Get /dev/sda1 parition offset
+    OFFSET=$( sfdisk -J disk.raw | jq '.partitiontable.partitions[0].start * 512' )
+
+    if [ -z $OFFSET ]; then
+        echo "failed to calculate offset"
+        exit 1
+    fi
 
     # Mount the disk locally
     OFFSET="$OFFSET" sh -c '\
diff --git a/tasks/google/add-ubuntu-16.04-32/task.yaml b/tasks/google/add-ubuntu-16.04-32/task.yaml
--- a/tasks/google/add-ubuntu-16.04-32/task.yaml
+++ b/tasks/google/add-ubuntu-16.04-32/task.yaml
@@ -18,8 +18,13 @@ execute: |
     wget $IMAGE_URL
     qemu-img convert -O raw "${IMAGE_URL##*/}" disk.raw
 
-    # Get /dev/sda1 parition offset:
-    OFFSET=$( sfdisk -J disk.raw | python -c 'import sys, json; a=json.load(sys.stdin); print(a["partitiontable"]["partitions"][0]["start"]*512)' )
+    # Get /dev/sda1 parition offset
+    OFFSET=$( sfdisk -J disk.raw | jq '.partitiontable.partitions[0].start * 512' )
+
+    if [ -z $OFFSET ]; then
+        echo "failed to calculate offset"
+        exit 1
+    fi
 
     # Make mounting directory and mount
     mkdir -p /mnt/disk
