new changes to update openstack images

diff --git a/.github/workflows/update_google.yaml b/.github/workflows/update_google.yaml
--- a/.github/workflows/update_google.yaml
+++ b/.github/workflows/update_google.yaml
@@ -1,4 +1,4 @@
-name: Weekly images update
+name: Weekly Google images update
 
 on:
   workflow_dispatch:
@@ -13,102 +13,79 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - group: ubuntu 14.04 (google)
+          - group: ubuntu 14.04
             task: ubuntu-14.04-64
             source: ubuntu-14.04-64
             target: ubuntu-14.04-64
-            cloud: google
-          - group: ubuntu 16.04 (google)
+          - group: ubuntu 16.04
             task: ubuntu-16.04-64
             source: ubuntu-16.04-64
             target: ubuntu-16.04-64
-            cloud: google
-          - group: ubuntu 18.04 (google)
+          - group: ubuntu 18.04
             task: ubuntu-18.04-64
             source: ubuntu-18.04-64
             target: ubuntu-18.04-64
-            cloud: google
-          - group: ubuntu 20.04 (google)
+          - group: ubuntu 20.04
             task: ubuntu-20.04-64
             source: ubuntu-20.04-64-base
             target: ubuntu-20.04-64
-            cloud: google
-          - group: ubuntu 22.04 (google)
+          - group: ubuntu 22.04
             task: ubuntu-22.04-64
             source: ubuntu-22.04-64-base
             target: ubuntu-22.04-64
-            cloud: google
-          - group: ubuntu 24.04 (google)
+          - group: ubuntu 24.04
             task: ubuntu-24.04-64
             source: ubuntu-24.04-64-base
             target: ubuntu-24.04-64
-            cloud: google
-          - group: ubuntu 24.10 (google)
+          - group: ubuntu 24.10
             task: ubuntu-24.10-64
             source: ubuntu-24.10-64-base
             target: ubuntu-24.10-64
-            cloud: google
 
-          - group: debian 11 (google)
+          - group: debian 11
             task: debian-11
             source: debian-11-64-base
             target: debian-11-64
-            cloud: google
-          - group: debian 12 (google)
+          - group: debian 12
             task: debian-12
             source: debian-12-64-base
             target: debian-12-64
-            cloud: google
-          - group: debian sid (google)
+          - group: debian sid
             task: debian-sid
             source: debian-sid-64-base
             target: debian-sid-64
-            cloud: google
 
-          - group: amazon linux 2 (google)
+          - group: amazon linux 2
             task: amazon-linux-2
             source: amazon-linux-2-64-base
             target: amazon-linux-2-64
-            cloud: google
-          - group: amazon linux 2023 (google)
+          - group: amazon linux 2023
             task: amazon-linux-2023
             source: amazon-linux-2023-64-base
             target: amazon-linux-2023-64
-            cloud: google
 
-          - group: centos 9 (google)
+          - group: centos 9
             task: centos-9
             source: centos-9-64-base
             target: centos-9-64
-            cloud: google
 
-          - group: opensuse 15.5 (google)
+          - group: opensuse 15.5
             task: opensuse-15-5
             source: opensuse-15.5-64-base
             target: opensuse-15.5-64
-            cloud: google
-          - group: opensuse 15.6 (google)
+          - group: opensuse 15.6
             task: opensuse-15-6
             source: opensuse-15.6-64-base
             target: opensuse-15.6-64
-            cloud: google
-          - group: opensuse tumbleweed (google)
+          - group: opensuse tumbleweed
             task: opensuse-tumbleweed
             source: opensuse-tumbleweed-64-base
             target: opensuse-tumbleweed-64
-            cloud: google
 
-          - group: arch linux (google)
+          - group: arch linux
             task: arch-linux
             source: arch-linux-64-base
             target: arch-linux-64
-            cloud: google
-
-          - group: fedora 39 (google)
-            task: fedora-39-64
-            source: fedora-39-64-base
-            target: fedora-39-64
-            cloud: google
 
     steps:
     - name: Ensure the workspace is clean
@@ -125,20 +102,12 @@ jobs:
       env:
           IMAGE_BAKER_SA: ${{ secrets.IMAGE_BAKER_SA }}
       run: |
-          if [ "${{ matrix.cloud }}" == google ]; then
-            echo "$IMAGE_BAKER_SA" > sa.json
-            if ! spread "${{ matrix.cloud }}:${{ matrix.source }}:tasks/${{ matrix.cloud }}/update-image/${{ matrix.task }}"; then
-              echo "Spread images task failed, exiting..."
-              exit 1
-            fi
-            spread "${{ matrix.cloud }}:${{ matrix.target }}:tasks/${{ matrix.cloud }}/common/clean-old-images"
-          elif [ "${{ matrix.cloud }}" == openstack ]; then
-              echo "Openstack updates not supported yet, exiting..."
-              exit 1
-          else
-              echo "${{ matrix.cloud }} updates not supported, exiting..."
-              exit 1
+          echo "$IMAGE_BAKER_SA" > sa.json
+          if ! spread "${{ matrix.cloud }}:${{ matrix.source }}:tasks/${{ matrix.cloud }}/update-image/${{ matrix.task }}"; then
+            echo "Spread images task failed, exiting..."
+            exit 1
           fi
+          spread "${{ matrix.cloud }}:${{ matrix.target }}:tasks/${{ matrix.cloud }}/common/clean-old-images"
   
     - name: Discard spread workers
       if: always()
